TestSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('update_app.urls')),
]

update_app/urls.py
from django.urls import path
from . import views

app_name = 'update_app'

urlpatterns = [
    path('', views.ListItems.as_view(), name="list_items"),
    path('update/<pk>', views.UpdateItems.as_view(), name="update_items"),
    path('create/', views.CreateItem.as_view(), name="create_item")
]

update_app/models.py
from django.db import models


class ClientDetails(models.Model):
    nome_do_cliente = models.CharField(max_length=256)
    data_de_nascimento = models.DateField()
    data_de_coleta = models.DateField()
    nome_do_medico = models.CharField(max_length=256)
    codigo_identificador = models.IntegerField()

update_app/views.py
from django.views.generic.edit import UpdateView, CreateView
from .models import ClientDetails
from django.urls import reverse_lazy
from django.views.generic import ListView


class CreateItem(CreateView):
    model = ClientDetails
    fields = '__all__'
    template_name = 'update_app/create_item.html'
    success_url = reverse_lazy('update_app:list_items')


class UpdateItems(UpdateView):
    model = ClientDetails
    context_object_name = 'product_list'
    template_name = 'update_app/update_items.html'
    fields = ['nome_do_cliente',
              'data_de_nascimento',
              'data_de_coleta',
              'nome_do_medico',
              'codigo_identificador']
    success_url = reverse_lazy('update_app:list_items')


class ListItems(ListView):
    model = ClientDetails
    context_object_name = 'product_list'
    template_name = 'update_app/list_items.html'

update_app/templates/update_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update App</title>
    <style>
        #main{
            display: flex;
            justify-content: center;
            align-items: center;
            flex-wrap: wrap;
            position: absolute;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
        }
        #main form input,
        #main form label,
        #main form button{
            width: 100%;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
<div id="main">
    {% block inner %}
    {% endblock %}
</div>

</body>
</html>

update_app/templates/update_app/create_item.html
{% extends 'update_app/base.html' %}

{% block inner %}
<form action="" method="POST" style="width: 50%">
    {% csrf_token %}
    <label for="nome_do_cliente_id">Nome do Cliente</label>
    <input type="text" id="nome_do_cliente_id" name="nome_do_cliente" required>
    <label for="data_de_nascimento_id">Data de Nascimento</label>
    <input type="date" id="data_de_nascimento_id" name="data_de_nascimento" required>
    <label for="data_de_coleta_id">Data de Coleta</label>
    <input type="date" id="data_de_coleta_id" name="data_de_coleta" required>
    <label for="nome_do_medico_id">Nome do Médico</label>
    <input type="text" id="nome_do_medico_id" name="nome_do_medico" required>
    <label for="codigo_identificador_id">Código Identificador</label>
    <input type="number" name="codigo_identificador" id="codigo_identificador_id" required>
    <button type="submit">Criar</button>
</form>
{% endblock %}

update_app/templates/update_app/list_items.html
{% extends 'update_app/base.html' %}

{% block inner %}
<style>
    tbody tr th{
        font-weight: normal;
    }
    table tr th{
        border: 1px solid;
        padding: 5px;
    }
    #new_user{
        right: 50px;
        top: 40px;
        position: absolute;
        border: 1px solid;
        text-decoration: unset;
        padding: 10px;
    }
</style>
<a id="new_user" href="{% url 'update_app:create_item' %}">Novo Usuário</a>
<table>
    <thead style="text-align: left;">
        <tr>
            <th>Nome do Cliente</th>
            <th>Data de Nascimento</th>
            <th>Data de Coleta</th>
            <th>Nome do Médico</th>
            <th>Código Identificador</th>
            <th>Atualizar Dados</th>
        </tr>
    </thead>
    <tbody>
        {% for item in product_list %}
        <tr>
            <th>{{ item.nome_do_cliente }}</th>
            <th>{{ item.data_de_nascimento }}</th>
            <th>{{ item.data_de_coleta }}</th>
            <th>{{ item.nome_do_medico }}</th>
            <th>{{ item.codigo_identificador }}</th>
            <th><a href="{% url 'update_app:update_items' item.pk %}">Atualizar Item</a></th>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

update_app/templates/update_app/login.html
{% extends 'update_app/base.html' %}

{% block inner %}
<form method="post">
    {% csrf_token %}
    <label for="username_id">Usuário</label>
    <input id="username_id" type="text" name="username">
    <label for="password_id">Senha</label>
    <input id="password_id" type="password" name="password">
    <button type="submit">Login</button>
</form>
{% endblock %}

update_app/templates/update_app/update_items.html
{% extends 'update_app/base.html' %}

{% block inner %}
<form action="" method="POST" style="width: 50%">
    {% csrf_token %}
    <label for="nome_do_cliente_id">Nome do Cliente</label>
    <input type="text" id="nome_do_cliente_id" name="nome_do_cliente" value="{{ product_list.nome_do_cliente }}" required>
    <label for="data_de_nascimento_id">Data de Nascimento</label>
    <input type="date" id="data_de_nascimento_id" name="data_de_nascimento" value="{{ product_list.data_de_nascimento|date:'Y-m-d' }}" required>
    <label for="data_de_coleta_id">Data de Coleta</label>
    <input type="date" id="data_de_coleta_id" name="data_de_coleta" value="{{ product_list.data_de_coleta|date:'Y-m-d' }}" required>
    <label for="nome_do_medico_id">Nome do Médico</label>
    <input type="text" id="nome_do_medico_id" name="nome_do_medico" value="{{ product_list.nome_do_medico }}" required>
    <label for="codigo_identificador_id">Código Identificador</label>
    <input type="number" name="codigo_identificador" id="codigo_identificador_id" value="{{ product_list.codigo_identificador }}" required>
    <button type="submit">Atualizar</button>
</form>
{% endblock %}